# Generated by Django 3.2 on 2023-02-06 09:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_notemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID, editable=False, primary_key=True, serialize=False),
        ),
    ]
