# Generated by Django 3.2 on 2023-02-06 09:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_alter_notemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
